# Generated by Django 3.1 on 2021-06-14 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210614_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Slug',
            new_name='slug',
        ),
    ]
